import { Image } from 'expo-image';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { GradientSafeAreaView as SafeAreaView } from '@/components/gradient-safe-area';
import { curriculum, type Lesson, type Subject } from '@/constants/curriculum';
import { useProgress } from '@/hooks/use-progress';

const astro = require('../../assets/BiosphereQuestAssets/Astro (Biosphere Quest Mascot).png');
const subjectKnowledge: Record<string, string> = { Math: 'Build number sense, solve problems, and connect math to real-life decisions.', Matter: 'Explore materials, their properties, and how matter changes.', 'Living Things & Environment': 'Study life, habitats, adaptations, and healthy ecosystems.', 'Force, Motion, & Energy': 'Discover how forces change motion and how energy moves.', 'Earth & Space': 'Understand Earth systems, weather, rocks, and space patterns.' };

export default function ExploreScreen() {
  const { completeLesson } = useProgress();
  const [grade, setGrade] = useState(1);
  const [selected, setSelected] = useState<{ subject: Subject; lesson: Lesson } | null>(null);
  if (selected) return <LessonDetail lesson={selected.lesson} subject={selected.subject} onBack={() => setSelected(null)} onComplete={() => completeLesson(40)} />;
  return <SafeAreaView style={styles.safeArea} edges={['top']}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.back}>‹ Cancel</Text><View style={styles.headerTitle}><Image source={astro} style={styles.headerMascot} /><Text style={styles.title}> My Courses</Text></View></View><View style={styles.search}><Text style={styles.searchText}>⌕ Search courses...</Text></View><View style={styles.gradeTabs}>{[1, 2, 3, 4, 5, 6].map((item) => <Pressable key={item} onPress={() => setGrade(item)} style={[styles.gradeTab, grade === item && styles.activeTab]}><Text style={styles.tabText}>Grade {item}</Text></Pressable>)}</View><Text style={styles.section}>Grade {grade} · Math and Science curriculum</Text>{curriculum[grade].map((subject) => <SubjectCard key={subject.title} subject={subject} onLesson={(lesson) => setSelected({ subject, lesson })} />)}</ScrollView></SafeAreaView>;
}
function SubjectCard({ subject, onLesson }: { subject: Subject; onLesson: (lesson: Lesson) => void }) { return <View style={[styles.subject, { borderColor: subject.color }]}><View style={styles.subjectHeader}><Text style={styles.subjectIcon}>{subject.icon}</Text><View style={styles.subjectCopy}><Text style={styles.subjectTitle}>{subject.title}</Text><Text style={styles.subjectSub}>{subject.lessons.length} lessons · Grade-ready missions</Text></View></View><Text style={styles.knowledge}>{subjectKnowledge[subject.title]}</Text>{subject.lessons.map((lesson, index) => <Pressable key={lesson.title} onPress={() => onLesson(lesson)} style={styles.lesson}><View style={styles.lessonNumber}><Text style={styles.lessonNumberText}>{index + 1}</Text></View><View style={styles.lessonCopy}><Text style={styles.lessonTitle}>{lesson.title}</Text><Text style={styles.lessonDifficulty}>{lesson.difficulty} challenge</Text></View><Text style={styles.lessonArrow}>›</Text></Pressable>)}</View>; }
function LessonDetail({ lesson, subject, onBack, onComplete }: { lesson: Lesson; subject: Subject; onBack: () => void; onComplete: () => void }) { return <SafeAreaView style={styles.safeArea} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ Back to courses</Text></Pressable><View style={[styles.lessonHero, { borderColor: subject.color }]}><Text style={styles.bigIcon}>{subject.icon}</Text><Text style={styles.detailTitle}>{lesson.title}</Text><Text style={styles.pill}>{lesson.difficulty} mission</Text></View><Info title="SUBJECT KNOWLEDGE" text={subjectKnowledge[subject.title]} /><Info title="DEFINITION" text={lesson.meaning} /><Info title="EXAMPLE" text={lesson.example} /><Pressable onPress={onComplete} style={styles.startButton}><Text style={styles.startText}>Complete lesson · +40 XP →</Text></Pressable></ScrollView></SafeAreaView>; }
function Info({ title, text }: { title: string; text: string }) { return <View style={styles.info}><Text style={styles.detailLabel}>{title}</Text><Text style={styles.detailBody}>{text}</Text></View>; }
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: '#091426' }, content: { padding: 18, paddingBottom: 40 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { color: '#e582ff', fontWeight: '800', fontSize: 14 }, headerTitle: { flexDirection: 'row', alignItems: 'center', gap: 7 }, headerMascot: { width: 40, height: 40 }, title: { color: '#fff', fontWeight: '900', fontSize: 21 }, search: { marginTop: 14, backgroundColor: '#30358d', borderColor: '#5c60ee', borderWidth: 1, borderRadius: 20, padding: 10 }, searchText: { color: '#cbc9f3', fontSize: 12 }, gradeTabs: { flexDirection: 'row', gap: 5, marginVertical: 12, flexWrap: 'wrap' }, gradeTab: { backgroundColor: '#252a69', borderRadius: 14, paddingHorizontal: 11, paddingVertical: 7 }, activeTab: { backgroundColor: '#6358ff' }, tabText: { color: '#fff', fontSize: 11, fontWeight: '800' }, section: { color: '#fff', fontWeight: '900', fontSize: 16, marginBottom: 9 }, subject: { backgroundColor: '#132844', borderWidth: 1, borderRadius: 17, padding: 10, marginBottom: 12 }, subjectHeader: { flexDirection: 'row', alignItems: 'center', gap: 9 }, subjectIcon: { fontSize: 25 }, subjectCopy: { flex: 1 }, subjectTitle: { color: '#fff', fontWeight: '900', fontSize: 14 }, subjectSub: { color: '#bcc8df', fontSize: 10, marginTop: 2 }, knowledge: { color: '#d7e1f2', fontSize: 10, lineHeight: 15, marginTop: 8 }, lesson: { backgroundColor: '#243d75', borderRadius: 11, padding: 8, flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 7 }, lessonNumber: { width: 27, height: 27, borderRadius: 15, backgroundColor: '#2b77ca', alignItems: 'center', justifyContent: 'center' }, lessonNumberText: { color: '#fff', fontWeight: '900' }, lessonCopy: { flex: 1 }, lessonTitle: { color: '#fff', fontWeight: '800', fontSize: 12 }, lessonDifficulty: { color: '#b9c9e5', fontSize: 9, marginTop: 2 }, lessonArrow: { color: '#fff', fontSize: 24 }, lessonHero: { alignItems: 'center', backgroundColor: '#182e5d', borderWidth: 1, borderRadius: 15, padding: 16 }, bigIcon: { fontSize: 40 }, detailTitle: { color: '#fff', fontSize: 21, fontWeight: '900', textAlign: 'center', marginTop: 7 }, pill: { color: '#9af2bc', fontWeight: '900', marginTop: 5 }, info: { backgroundColor: '#30358d', borderColor: '#5d62ef', borderWidth: 1, borderRadius: 14, padding: 14, marginTop: 12 }, detailLabel: { color: '#f3ca45', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, detailBody: { color: '#fff', fontSize: 15, lineHeight: 23, marginTop: 8 }, startButton: { backgroundColor: '#6258ff', borderRadius: 10, alignItems: 'center', padding: 13, marginTop: 16 }, startText: { color: '#fff', fontWeight: '900' } });
